# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main", "feature/*" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run Unit Tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test --stacktrace --warning-mode=all
      - name: Install Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          build-tools: 30.0.3
      - name: Start Emulator
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: default
          arch: x86_64
          profile: Nexus 6
          emulator-options: "-no-window -no-audio"
          script: echo "Emulator started"
      - name: Wait for Emulator to Boot
        run: |
          adb wait-for-device
          echo "Waiting for emulator to fully boot..."
          for i in {1..10}; do
            if adb shell getprop sys.boot_completed | grep -m 1 '1'; then
              echo "Emulator is ready!"
              exit 0
            fi
            echo "Emulator is still booting, waiting..."
            sleep 10
          done
          echo "Emulator failed to boot within the timeout!"
          exit 1
      - name: Run Instrumentation Tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ./gradlew connectedAndroidTest --stacktrace